# Generated by Django 3.1.5 on 2021-02-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bikes_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikes',
            options={'verbose_name': 'bike', 'verbose_name_plural': 'bikes'},
        ),
    ]
